name: Deploy Client

on:
  push:
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and Deploy
      run: |
        cd ~/aiccmap_project/client && \
        git pull && \
        docker stop client_container || true && \
        docker rm client_container || true && \
        docker build -t client_image . && \
        docker run -d --name client_container -p 3000:3000 client_image
